### ISSUE TITLE
how to deploy yurita on production

### ISSUE THREAD

**Issue by pint12** [paypal/yurita#48]
gr* talk on Reversim 2019
there are no guidelines on how to deploy yurita on production env. 

how does it interact with spark?
is it only using the standalone mode? or can it be integrated with a spark cluster ? or EMR?

**Comment by urisilberstein** [comment]
Thanks! 
Yurita is a framework that enhances spark by adding anomaly detection capabilities. Meaning that essentially it is a spark (structured streaming) application that needs to get deployed, so you can use the guidelines that your organization has for deploying spark applications. 
And it supports all spark modes also yarn and not only standalone.
